(ns common-beer-format.generative.recipes-test
  (:require [clojure.test :refer :all]
            [common-beer-format.generative.util :as gen]
            [common-beer-format.recipes :as recipes]))


(deftest valid-generators-test
  (testing "Ensure all generators work out of the box"
    (is (gen/generatable? ::recipes/primary-temp))
    (is (gen/generatable? ::recipes/asst-brewer))
    (is (gen/generatable? ::recipes/display-og))
    (is (gen/generatable? ::recipes/secondary-age))
    (is (gen/generatable? ::recipes/og))
    (is (gen/generatable? ::recipes/display-primary-temp))
    (is (gen/generatable? ::recipes/abv))
    (is (gen/generatable? ::recipes/recipes))
    (is (gen/generatable? ::recipes/est-color))
    (is (gen/generatable? ::recipes/boil-time))
    (is (gen/generatable? ::recipes/boil-size))
    (is (gen/generatable? ::recipes/display-carb-temp))
    (is (gen/generatable? ::recipes/batch-size))
    (is (gen/generatable? ::recipes/est-fg))
    (is (gen/generatable? ::recipes/display-boil-size))
    (is (gen/generatable? ::recipes/tertiary-age))
    (is (gen/generatable? ::recipes/priming-sugar-equiv))
    (is (gen/generatable? ::recipes/display-secondary-temp))
    (is (gen/generatable? ::recipes/brewer))
    (is (gen/generatable? ::recipes/taste-notes))
    (is (gen/generatable? ::recipes/recipes-wrapper))
    (is (gen/generatable? ::recipes/display-tertiary-temp))
    (is (gen/generatable? ::recipes/age))
    (is (gen/generatable? ::recipes/tertiary-temp))
    (is (gen/generatable? ::recipes/fermentation-stages))
    (is (gen/generatable? ::recipes/recipe))
    (is (gen/generatable? ::recipes/primary-age))
    (is (gen/generatable? ::recipes/carbonation))
    (is (gen/generatable? ::recipes/fg))
    (is (gen/generatable? ::recipes/date))
    (is (gen/generatable? ::recipes/display-batch-size))
    (is (gen/generatable? ::recipes/taste-rating))
    (is (gen/generatable? ::recipes/display-age-temp))
    (is (gen/generatable? ::recipes/est-og))
    (is (gen/generatable? ::recipes/age-temp))
    (is (gen/generatable? ::recipes/priming-sugar-name))
    (is (gen/generatable? ::recipes/est-abv))
    (is (gen/generatable? ::recipes/secondary-temp))
    (is (gen/generatable? ::recipes/efficiency))
    (is (gen/generatable? ::recipes/ibu-method))
    (is (gen/generatable? ::recipes/calories))
    (is (gen/generatable? ::recipes/display-fg))
    (is (gen/generatable? ::recipes/carbonation-temp))
    (is (gen/generatable? ::recipes/forced-carbonation))
    (is (gen/generatable? ::recipes/carbonation-used))
    (is (gen/generatable? ::recipes/recipe-wrapper))
    (is (gen/generatable? ::recipes/actual-efficiency))
    (is (gen/generatable? ::recipes/keg-priming-factor))
    (is (gen/generatable? ::recipes/type))
    (is (gen/generatable? ::recipes/ibu))))
