name: Test Reporter

on: ["pull_request"]

jobs:
  test-reporter:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3.0.2

    - name: Cache maven dependencies
      uses: actions/cache@v2
      env:
          cache-name: cache-maven
      with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}

    - name: Install Clojure dependencies
      run: lein deps

    - name: Run tests
      run: lein cloverage --junit

    - name: Report Results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Checker
        path: target/coverage/junit.xml
        reporter: java-junit
        token: ${{ secrets.WALL_BREW_BOT_PAT }}
